// @generated by packetframe-vpp-api-codegen. DO NOT EDIT.
//
// Source: crates/modules/vpp-offload/vpp-api/*.api.json, vendored from
// the pinned VPP release's published API bundle. Regenerate with:
//   cargo run -p packetframe-vpp-api-codegen -- \
//     crates/modules/vpp-offload/vpp-api \
//     crates/modules/vpp-offload/src/vpp_api/generated.rs
// CI re-runs this and diffs, so a pin bump that changes the wire
// format fails the build rather than corrupting a FIB.
#![allow(clippy::all, dead_code, non_camel_case_types)]

use super::codec::{Decode, Decoder, Encode, Message, MessageMeta, WireError};

/// `(name, crc, context_offset, client_index_precedes_context)`
/// for every message this client speaks.
///
/// `context_offset` is where `context` sits in the full wire
/// payload; the transport needs it to correlate a reply before
/// it knows the message type. It is NOT constant: replies with
/// a leading client_index put context at 6, most at 2.
pub const MESSAGE_META: &[MessageMeta] = &[
    MessageMeta { name: "sockclnt_create", crc: "0x455fb9c4", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "sockclnt_create_reply", crc: "0x35166268", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "sockclnt_delete", crc: "0x8ac76db6", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "sockclnt_delete_reply", crc: "0x8f38b1ee", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "control_ping", crc: "0x51077d14", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "control_ping_reply", crc: "0xf6b0b8ca", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "ip_route_add_del", crc: "0xb8ecfe0d", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "ip_route_add_del_reply", crc: "0x1992deab", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "ip_route_lookup", crc: "0x710d6471", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "ip_route_lookup_reply", crc: "0x5d8febcb", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "ip_neighbor_add_del", crc: "0x0607c257", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "ip_neighbor_add_del_reply", crc: "0x1992deab", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "sw_interface_set_flags", crc: "0xf5aec1b8", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "sw_interface_set_flags_reply", crc: "0xe8d4e804", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "dev_attach", crc: "0x44b725fc", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "dev_attach_reply", crc: "0x6082b181", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "dev_detach", crc: "0xafae52d6", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "dev_detach_reply", crc: "0xc8d74455", context_offset: 2, client_index_prefix: false },
    MessageMeta { name: "dev_create_port_if", crc: "0xdbdf06f3", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "dev_create_port_if_reply", crc: "0x243c2374", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "dev_remove_port_if", crc: "0x529cb13f", context_offset: 6, client_index_prefix: true },
    MessageMeta { name: "dev_remove_port_if_reply", crc: "0xc8d74455", context_offset: 2, client_index_prefix: false },
];

// enum address_family : u8
pub const ADDRESS_IP4: u8 = 0;
pub const ADDRESS_IP6: u8 = 1;

// enum dev_flags : u32
pub const VL_API_DEV_FLAG_NO_STATS: u32 = 1;

// enum dev_port_flags : u32
pub const VL_API_DEV_PORT_FLAG_INTERRUPT_MODE: u32 = 1;
pub const VL_API_DEV_PORT_FLAG_CONSISTENT_QP: u32 = 2;

// enum fib_path_flags : u32
pub const FIB_API_PATH_FLAG_NONE: u32 = 0;
pub const FIB_API_PATH_FLAG_RESOLVE_VIA_ATTACHED: u32 = 1;
pub const FIB_API_PATH_FLAG_RESOLVE_VIA_HOST: u32 = 2;
pub const FIB_API_PATH_FLAG_POP_PW_CW: u32 = 4;

// enum fib_path_nh_proto : u32
pub const FIB_API_PATH_NH_PROTO_IP4: u32 = 0;
pub const FIB_API_PATH_NH_PROTO_IP6: u32 = 1;
pub const FIB_API_PATH_NH_PROTO_MPLS: u32 = 2;
pub const FIB_API_PATH_NH_PROTO_ETHERNET: u32 = 3;
pub const FIB_API_PATH_NH_PROTO_BIER: u32 = 4;

// enum fib_path_type : u32
pub const FIB_API_PATH_TYPE_NORMAL: u32 = 0;
pub const FIB_API_PATH_TYPE_LOCAL: u32 = 1;
pub const FIB_API_PATH_TYPE_DROP: u32 = 2;
pub const FIB_API_PATH_TYPE_UDP_ENCAP: u32 = 3;
pub const FIB_API_PATH_TYPE_BIER_IMP: u32 = 4;
pub const FIB_API_PATH_TYPE_ICMP_UNREACH: u32 = 5;
pub const FIB_API_PATH_TYPE_ICMP_PROHIBIT: u32 = 6;
pub const FIB_API_PATH_TYPE_SOURCE_LOOKUP: u32 = 7;
pub const FIB_API_PATH_TYPE_DVR: u32 = 8;
pub const FIB_API_PATH_TYPE_INTERFACE_RX: u32 = 9;
pub const FIB_API_PATH_TYPE_CLASSIFY: u32 = 10;

// enum if_status_flags : u32
pub const IF_STATUS_API_FLAG_ADMIN_UP: u32 = 1;
pub const IF_STATUS_API_FLAG_LINK_UP: u32 = 2;

// enum ip_neighbor_flags : u8
pub const IP_API_NEIGHBOR_FLAG_NONE: u8 = 0;
pub const IP_API_NEIGHBOR_FLAG_STATIC: u8 = 1;
pub const IP_API_NEIGHBOR_FLAG_NO_FIB_ENTRY: u8 = 2;

/// `address_union` — fixed 16-byte union overlay.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AddressUnion(pub [u8; 16]);

impl Default for AddressUnion {
    fn default() -> Self { Self([0u8; 16]) }
}

impl Encode for AddressUnion {
    fn encode(&self, buf: &mut Vec<u8>) { buf.extend_from_slice(&self.0); }
}

impl Decode for AddressUnion {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> { Ok(Self(d.bytes::<16>()?)) }
}

/// `address` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Address {
    pub af: u8,
    pub un: AddressUnion,
}

impl Encode for Address {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.af as u8).to_be_bytes());
        self.un.encode(buf);
    }
}

impl Decode for Address {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let af = d.u8()?;
        let un = AddressUnion::decode(d)?;
        Ok(Self {
            af,
            un,
        })
    }
}

/// `fib_mpls_label` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FibMplsLabel {
    pub is_uniform: u8,
    pub label: u32,
    pub ttl: u8,
    pub exp: u8,
}

impl Encode for FibMplsLabel {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.is_uniform).to_be_bytes());
        buf.extend_from_slice(&(self.label).to_be_bytes());
        buf.extend_from_slice(&(self.ttl).to_be_bytes());
        buf.extend_from_slice(&(self.exp).to_be_bytes());
    }
}

impl Decode for FibMplsLabel {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let is_uniform = d.u8()?;
        let label = d.u32()?;
        let ttl = d.u8()?;
        let exp = d.u8()?;
        Ok(Self {
            is_uniform,
            label,
            ttl,
            exp,
        })
    }
}

/// `fib_path` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FibPath {
    pub sw_if_index: u32,
    pub table_id: u32,
    pub rpf_id: u32,
    pub weight: u8,
    pub preference: u8,
    pub r#type: u32,
    pub flags: u32,
    pub proto: u32,
    pub nh: FibPathNh,
    pub n_labels: u8,
    pub label_stack: [FibMplsLabel; 16],
}

impl Encode for FibPath {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.sw_if_index).to_be_bytes());
        buf.extend_from_slice(&(self.table_id).to_be_bytes());
        buf.extend_from_slice(&(self.rpf_id).to_be_bytes());
        buf.extend_from_slice(&(self.weight).to_be_bytes());
        buf.extend_from_slice(&(self.preference).to_be_bytes());
        buf.extend_from_slice(&(self.r#type as u32).to_be_bytes());
        buf.extend_from_slice(&(self.flags as u32).to_be_bytes());
        buf.extend_from_slice(&(self.proto as u32).to_be_bytes());
        self.nh.encode(buf);
        buf.extend_from_slice(&(self.n_labels).to_be_bytes());
        for it in self.label_stack.iter() {
        it.encode(buf);
        }
    }
}

impl Decode for FibPath {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let sw_if_index = d.u32()?;
        let table_id = d.u32()?;
        let rpf_id = d.u32()?;
        let weight = d.u8()?;
        let preference = d.u8()?;
        let r#type = d.u32()?;
        let flags = d.u32()?;
        let proto = d.u32()?;
        let nh = FibPathNh::decode(d)?;
        let n_labels = d.u8()?;
        let label_stack = {
            let mut a = <[_; 16]>::default();
            for slot in a.iter_mut() {
                *slot = FibMplsLabel::decode(d)?;
            }
            a
        };
        Ok(Self {
            sw_if_index,
            table_id,
            rpf_id,
            weight,
            preference,
            r#type,
            flags,
            proto,
            nh,
            n_labels,
            label_stack,
        })
    }
}

/// `fib_path_nh` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FibPathNh {
    pub address: AddressUnion,
    pub via_label: u32,
    pub obj_id: u32,
    pub classify_table_index: u32,
}

impl Encode for FibPathNh {
    fn encode(&self, buf: &mut Vec<u8>) {
        self.address.encode(buf);
        buf.extend_from_slice(&(self.via_label).to_be_bytes());
        buf.extend_from_slice(&(self.obj_id).to_be_bytes());
        buf.extend_from_slice(&(self.classify_table_index).to_be_bytes());
    }
}

impl Decode for FibPathNh {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let address = AddressUnion::decode(d)?;
        let via_label = d.u32()?;
        let obj_id = d.u32()?;
        let classify_table_index = d.u32()?;
        Ok(Self {
            address,
            via_label,
            obj_id,
            classify_table_index,
        })
    }
}

/// `ip_neighbor` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpNeighbor {
    pub sw_if_index: u32,
    pub flags: u8,
    pub mac_address: [u8; 6],
    pub ip_address: Address,
}

impl Encode for IpNeighbor {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.sw_if_index).to_be_bytes());
        buf.extend_from_slice(&(self.flags as u8).to_be_bytes());
        buf.extend_from_slice(&self.mac_address[..]);
        self.ip_address.encode(buf);
    }
}

impl Decode for IpNeighbor {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let sw_if_index = d.u32()?;
        let flags = d.u8()?;
        let mac_address = d.bytes::<6>()?;
        let ip_address = Address::decode(d)?;
        Ok(Self {
            sw_if_index,
            flags,
            mac_address,
            ip_address,
        })
    }
}

/// `ip_route` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpRoute {
    pub table_id: u32,
    pub stats_index: u32,
    pub prefix: Prefix,
    pub n_paths: u8,
    pub paths: Vec<FibPath>,
}

impl Encode for IpRoute {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.table_id).to_be_bytes());
        buf.extend_from_slice(&(self.stats_index).to_be_bytes());
        self.prefix.encode(buf);
        buf.extend_from_slice(&(self.paths.len() as u8).to_be_bytes());
        for it in &self.paths {
        it.encode(buf);
        }
    }
}

impl Decode for IpRoute {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let table_id = d.u32()?;
        let stats_index = d.u32()?;
        let prefix = Prefix::decode(d)?;
        let n_paths = d.u8()?;
        let paths = {
            let n = n_paths as usize;
            let mut v = Vec::with_capacity(n.min(1 << 16));
            for _ in 0..n {
                v.push(FibPath::decode(d)?);
            }
            v
        };
        Ok(Self {
            table_id,
            stats_index,
            prefix,
            n_paths,
            paths,
        })
    }
}

/// `message_table_entry` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MessageTableEntry {
    pub index: u16,
    pub name: String,
}

impl Encode for MessageTableEntry {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.index).to_be_bytes());
        {
            let mut tmp = [0u8; 64];
            let b = self.name.as_bytes();
            let k = b.len().min(64);
            tmp[..k].copy_from_slice(&b[..k]);
            buf.extend_from_slice(&tmp);
        }
    }
}

impl Decode for MessageTableEntry {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let index = d.u16()?;
        let name = d.string_fixed(64)?;
        Ok(Self {
            index,
            name,
        })
    }
}

/// `prefix` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Prefix {
    pub address: Address,
    pub len: u8,
}

impl Encode for Prefix {
    fn encode(&self, buf: &mut Vec<u8>) {
        self.address.encode(buf);
        buf.extend_from_slice(&(self.len).to_be_bytes());
    }
}

impl Decode for Prefix {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let address = Address::decode(d)?;
        let len = d.u8()?;
        Ok(Self {
            address,
            len,
        })
    }
}

/// `sockclnt_create` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SockclntCreate {
    pub context: u32,
    pub name: String,
}

impl Encode for SockclntCreate {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        {
            let mut tmp = [0u8; 64];
            let b = self.name.as_bytes();
            let k = b.len().min(64);
            tmp[..k].copy_from_slice(&b[..k]);
            buf.extend_from_slice(&tmp);
        }
    }
}

impl Decode for SockclntCreate {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let name = d.string_fixed(64)?;
        Ok(Self {
            context,
            name,
        })
    }
}

impl Message for SockclntCreate {
    const NAME: &'static str = "sockclnt_create";
    const CRC: &'static str = "0x455fb9c4";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `sockclnt_create_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SockclntCreateReply {
    pub context: u32,
    pub response: i32,
    pub index: u32,
    pub count: u16,
    pub message_table: Vec<MessageTableEntry>,
}

impl Encode for SockclntCreateReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.response).to_be_bytes());
        buf.extend_from_slice(&(self.index).to_be_bytes());
        buf.extend_from_slice(&(self.message_table.len() as u16).to_be_bytes());
        for it in &self.message_table {
        it.encode(buf);
        }
    }
}

impl Decode for SockclntCreateReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let response = d.i32()?;
        let index = d.u32()?;
        let count = d.u16()?;
        let message_table = {
            let n = count as usize;
            let mut v = Vec::with_capacity(n.min(1 << 16));
            for _ in 0..n {
                v.push(MessageTableEntry::decode(d)?);
            }
            v
        };
        Ok(Self {
            context,
            response,
            index,
            count,
            message_table,
        })
    }
}

impl Message for SockclntCreateReply {
    const NAME: &'static str = "sockclnt_create_reply";
    const CRC: &'static str = "0x35166268";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `sockclnt_delete` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SockclntDelete {
    pub context: u32,
    pub index: u32,
}

impl Encode for SockclntDelete {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.index).to_be_bytes());
    }
}

impl Decode for SockclntDelete {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let index = d.u32()?;
        Ok(Self {
            context,
            index,
        })
    }
}

impl Message for SockclntDelete {
    const NAME: &'static str = "sockclnt_delete";
    const CRC: &'static str = "0x8ac76db6";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `sockclnt_delete_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SockclntDeleteReply {
    pub context: u32,
    pub response: i32,
}

impl Encode for SockclntDeleteReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.response).to_be_bytes());
    }
}

impl Decode for SockclntDeleteReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let response = d.i32()?;
        Ok(Self {
            context,
            response,
        })
    }
}

impl Message for SockclntDeleteReply {
    const NAME: &'static str = "sockclnt_delete_reply";
    const CRC: &'static str = "0x8f38b1ee";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `control_ping` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ControlPing {
    pub context: u32,
}

impl Encode for ControlPing {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
    }
}

impl Decode for ControlPing {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        Ok(Self {
            context,
        })
    }
}

impl Message for ControlPing {
    const NAME: &'static str = "control_ping";
    const CRC: &'static str = "0x51077d14";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `control_ping_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ControlPingReply {
    pub context: u32,
    pub retval: i32,
    pub vpe_pid: u32,
}

impl Encode for ControlPingReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.vpe_pid).to_be_bytes());
    }
}

impl Decode for ControlPingReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        let _ = d.u32()?;
        let vpe_pid = d.u32()?;
        Ok(Self {
            context,
            retval,
            vpe_pid,
        })
    }
}

impl Message for ControlPingReply {
    const NAME: &'static str = "control_ping_reply";
    const CRC: &'static str = "0xf6b0b8ca";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `ip_route_add_del` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpRouteAddDel {
    pub context: u32,
    pub is_add: bool,
    pub is_multipath: bool,
    pub route: IpRoute,
}

impl Encode for IpRouteAddDel {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.push(if self.is_add { 1u8 } else { 0u8 });
        buf.push(if self.is_multipath { 1u8 } else { 0u8 });
        self.route.encode(buf);
    }
}

impl Decode for IpRouteAddDel {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let is_add = d.bool()?;
        let is_multipath = d.bool()?;
        let route = IpRoute::decode(d)?;
        Ok(Self {
            context,
            is_add,
            is_multipath,
            route,
        })
    }
}

impl Message for IpRouteAddDel {
    const NAME: &'static str = "ip_route_add_del";
    const CRC: &'static str = "0xb8ecfe0d";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `ip_route_add_del_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpRouteAddDelReply {
    pub context: u32,
    pub retval: i32,
    pub stats_index: u32,
}

impl Encode for IpRouteAddDelReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.stats_index).to_be_bytes());
    }
}

impl Decode for IpRouteAddDelReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        let stats_index = d.u32()?;
        Ok(Self {
            context,
            retval,
            stats_index,
        })
    }
}

impl Message for IpRouteAddDelReply {
    const NAME: &'static str = "ip_route_add_del_reply";
    const CRC: &'static str = "0x1992deab";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `ip_route_lookup` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpRouteLookup {
    pub context: u32,
    pub table_id: u32,
    pub exact: u8,
    pub prefix: Prefix,
}

impl Encode for IpRouteLookup {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.table_id).to_be_bytes());
        buf.extend_from_slice(&(self.exact).to_be_bytes());
        self.prefix.encode(buf);
    }
}

impl Decode for IpRouteLookup {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let table_id = d.u32()?;
        let exact = d.u8()?;
        let prefix = Prefix::decode(d)?;
        Ok(Self {
            context,
            table_id,
            exact,
            prefix,
        })
    }
}

impl Message for IpRouteLookup {
    const NAME: &'static str = "ip_route_lookup";
    const CRC: &'static str = "0x710d6471";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `ip_route_lookup_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpRouteLookupReply {
    pub context: u32,
    pub retval: i32,
    pub route: IpRoute,
}

impl Encode for IpRouteLookupReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        self.route.encode(buf);
    }
}

impl Decode for IpRouteLookupReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        let route = IpRoute::decode(d)?;
        Ok(Self {
            context,
            retval,
            route,
        })
    }
}

impl Message for IpRouteLookupReply {
    const NAME: &'static str = "ip_route_lookup_reply";
    const CRC: &'static str = "0x5d8febcb";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `ip_neighbor_add_del` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpNeighborAddDel {
    pub context: u32,
    pub is_add: bool,
    pub neighbor: IpNeighbor,
}

impl Encode for IpNeighborAddDel {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.push(if self.is_add { 1u8 } else { 0u8 });
        self.neighbor.encode(buf);
    }
}

impl Decode for IpNeighborAddDel {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let is_add = d.bool()?;
        let neighbor = IpNeighbor::decode(d)?;
        Ok(Self {
            context,
            is_add,
            neighbor,
        })
    }
}

impl Message for IpNeighborAddDel {
    const NAME: &'static str = "ip_neighbor_add_del";
    const CRC: &'static str = "0x0607c257";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `ip_neighbor_add_del_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct IpNeighborAddDelReply {
    pub context: u32,
    pub retval: i32,
    pub stats_index: u32,
}

impl Encode for IpNeighborAddDelReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.stats_index).to_be_bytes());
    }
}

impl Decode for IpNeighborAddDelReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        let stats_index = d.u32()?;
        Ok(Self {
            context,
            retval,
            stats_index,
        })
    }
}

impl Message for IpNeighborAddDelReply {
    const NAME: &'static str = "ip_neighbor_add_del_reply";
    const CRC: &'static str = "0x1992deab";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `sw_interface_set_flags` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SwInterfaceSetFlags {
    pub context: u32,
    pub sw_if_index: u32,
    pub flags: u32,
}

impl Encode for SwInterfaceSetFlags {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.sw_if_index).to_be_bytes());
        buf.extend_from_slice(&(self.flags as u32).to_be_bytes());
    }
}

impl Decode for SwInterfaceSetFlags {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let sw_if_index = d.u32()?;
        let flags = d.u32()?;
        Ok(Self {
            context,
            sw_if_index,
            flags,
        })
    }
}

impl Message for SwInterfaceSetFlags {
    const NAME: &'static str = "sw_interface_set_flags";
    const CRC: &'static str = "0xf5aec1b8";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `sw_interface_set_flags_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SwInterfaceSetFlagsReply {
    pub context: u32,
    pub retval: i32,
}

impl Encode for SwInterfaceSetFlagsReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
    }
}

impl Decode for SwInterfaceSetFlagsReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        Ok(Self {
            context,
            retval,
        })
    }
}

impl Message for SwInterfaceSetFlagsReply {
    const NAME: &'static str = "sw_interface_set_flags_reply";
    const CRC: &'static str = "0xe8d4e804";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_attach` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevAttach {
    pub context: u32,
    pub device_id: String,
    pub driver_name: String,
    pub flags: u32,
    pub args: String,
}

impl Encode for DevAttach {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        {
            let mut tmp = [0u8; 48];
            let b = self.device_id.as_bytes();
            let k = b.len().min(48);
            tmp[..k].copy_from_slice(&b[..k]);
            buf.extend_from_slice(&tmp);
        }
        {
            let mut tmp = [0u8; 16];
            let b = self.driver_name.as_bytes();
            let k = b.len().min(16);
            tmp[..k].copy_from_slice(&b[..k]);
            buf.extend_from_slice(&tmp);
        }
        buf.extend_from_slice(&(self.flags as u32).to_be_bytes());
        buf.extend_from_slice(&(self.args.len() as u32).to_be_bytes());
        buf.extend_from_slice(self.args.as_bytes());
    }
}

impl Decode for DevAttach {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let device_id = d.string_fixed(48)?;
        let driver_name = d.string_fixed(16)?;
        let flags = d.u32()?;
        let args = d.string_var()?;
        Ok(Self {
            context,
            device_id,
            driver_name,
            flags,
            args,
        })
    }
}

impl Message for DevAttach {
    const NAME: &'static str = "dev_attach";
    const CRC: &'static str = "0x44b725fc";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_attach_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevAttachReply {
    pub context: u32,
    pub dev_index: u32,
    pub retval: i32,
    pub error_string: String,
}

impl Encode for DevAttachReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.dev_index).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.error_string.len() as u32).to_be_bytes());
        buf.extend_from_slice(self.error_string.as_bytes());
    }
}

impl Decode for DevAttachReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let dev_index = d.u32()?;
        let retval = d.i32()?;
        let error_string = d.string_var()?;
        Ok(Self {
            context,
            dev_index,
            retval,
            error_string,
        })
    }
}

impl Message for DevAttachReply {
    const NAME: &'static str = "dev_attach_reply";
    const CRC: &'static str = "0x6082b181";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_detach` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevDetach {
    pub context: u32,
    pub dev_index: u32,
}

impl Encode for DevDetach {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.dev_index).to_be_bytes());
    }
}

impl Decode for DevDetach {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let dev_index = d.u32()?;
        Ok(Self {
            context,
            dev_index,
        })
    }
}

impl Message for DevDetach {
    const NAME: &'static str = "dev_detach";
    const CRC: &'static str = "0xafae52d6";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_detach_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevDetachReply {
    pub context: u32,
    pub retval: i32,
    pub error_string: String,
}

impl Encode for DevDetachReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.error_string.len() as u32).to_be_bytes());
        buf.extend_from_slice(self.error_string.as_bytes());
    }
}

impl Decode for DevDetachReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        let error_string = d.string_var()?;
        Ok(Self {
            context,
            retval,
            error_string,
        })
    }
}

impl Message for DevDetachReply {
    const NAME: &'static str = "dev_detach_reply";
    const CRC: &'static str = "0xc8d74455";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_create_port_if` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevCreatePortIf {
    pub context: u32,
    pub dev_index: u32,
    pub intf_name: String,
    pub num_rx_queues: u16,
    pub num_tx_queues: u16,
    pub rx_queue_size: u16,
    pub tx_queue_size: u16,
    pub port_id: u16,
    pub flags: u32,
    pub args: String,
}

impl Encode for DevCreatePortIf {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.dev_index).to_be_bytes());
        {
            let mut tmp = [0u8; 32];
            let b = self.intf_name.as_bytes();
            let k = b.len().min(32);
            tmp[..k].copy_from_slice(&b[..k]);
            buf.extend_from_slice(&tmp);
        }
        buf.extend_from_slice(&(self.num_rx_queues).to_be_bytes());
        buf.extend_from_slice(&(self.num_tx_queues).to_be_bytes());
        buf.extend_from_slice(&(self.rx_queue_size).to_be_bytes());
        buf.extend_from_slice(&(self.tx_queue_size).to_be_bytes());
        buf.extend_from_slice(&(self.port_id).to_be_bytes());
        buf.extend_from_slice(&(self.flags as u32).to_be_bytes());
        buf.extend_from_slice(&(self.args.len() as u32).to_be_bytes());
        buf.extend_from_slice(self.args.as_bytes());
    }
}

impl Decode for DevCreatePortIf {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let dev_index = d.u32()?;
        let intf_name = d.string_fixed(32)?;
        let num_rx_queues = d.u16()?;
        let num_tx_queues = d.u16()?;
        let rx_queue_size = d.u16()?;
        let tx_queue_size = d.u16()?;
        let port_id = d.u16()?;
        let flags = d.u32()?;
        let args = d.string_var()?;
        Ok(Self {
            context,
            dev_index,
            intf_name,
            num_rx_queues,
            num_tx_queues,
            rx_queue_size,
            tx_queue_size,
            port_id,
            flags,
            args,
        })
    }
}

impl Message for DevCreatePortIf {
    const NAME: &'static str = "dev_create_port_if";
    const CRC: &'static str = "0xdbdf06f3";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_create_port_if_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevCreatePortIfReply {
    pub context: u32,
    pub sw_if_index: u32,
    pub retval: i32,
    pub error_string: String,
}

impl Encode for DevCreatePortIfReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.sw_if_index).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.error_string.len() as u32).to_be_bytes());
        buf.extend_from_slice(self.error_string.as_bytes());
    }
}

impl Decode for DevCreatePortIfReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let sw_if_index = d.u32()?;
        let retval = d.i32()?;
        let error_string = d.string_var()?;
        Ok(Self {
            context,
            sw_if_index,
            retval,
            error_string,
        })
    }
}

impl Message for DevCreatePortIfReply {
    const NAME: &'static str = "dev_create_port_if_reply";
    const CRC: &'static str = "0x243c2374";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_remove_port_if` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevRemovePortIf {
    pub context: u32,
    pub sw_if_index: u32,
}

impl Encode for DevRemovePortIf {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.sw_if_index).to_be_bytes());
    }
}

impl Decode for DevRemovePortIf {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let _ = d.u32()?;
        let context = d.u32()?;
        let sw_if_index = d.u32()?;
        Ok(Self {
            context,
            sw_if_index,
        })
    }
}

impl Message for DevRemovePortIf {
    const NAME: &'static str = "dev_remove_port_if";
    const CRC: &'static str = "0x529cb13f";
    const CONTEXT_OFFSET: usize = 6;
    const CLIENT_INDEX_PREFIX: bool = true;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

/// `dev_remove_port_if_reply` — generated from the pinned .api.json.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DevRemovePortIfReply {
    pub context: u32,
    pub retval: i32,
    pub error_string: String,
}

impl Encode for DevRemovePortIfReply {
    fn encode(&self, buf: &mut Vec<u8>) {
        buf.extend_from_slice(&(self.context).to_be_bytes());
        buf.extend_from_slice(&(self.retval).to_be_bytes());
        buf.extend_from_slice(&(self.error_string.len() as u32).to_be_bytes());
        buf.extend_from_slice(self.error_string.as_bytes());
    }
}

impl Decode for DevRemovePortIfReply {
    fn decode(d: &mut Decoder<'_>) -> Result<Self, WireError> {
        let _ = d.u16()?;
        let context = d.u32()?;
        let retval = d.i32()?;
        let error_string = d.string_var()?;
        Ok(Self {
            context,
            retval,
            error_string,
        })
    }
}

impl Message for DevRemovePortIfReply {
    const NAME: &'static str = "dev_remove_port_if_reply";
    const CRC: &'static str = "0xc8d74455";
    const CONTEXT_OFFSET: usize = 2;
    const CLIENT_INDEX_PREFIX: bool = false;
    fn set_context(&mut self, context: u32) { self.context = context; }
}

